### ISSUE TITLE
Circle items orientation

### ISSUE THREAD

**Issue by Glennmen** [leshchenko/CircularLayoutManager#3]
I am creating a circular menu with items but for some reason this library is showing them in reverse order. Is it possible to add some kind of orientation to add customisation flexibility to this library.

The Back button should be the first item and the Input item should be last:
![IMG_20191007_160941](https://user-images.githubusercontent.com/11406433/66319355-4441d800-e91d-11e9-972a-bf0d1280a249.jpg)

**Comment by leshchenko** [comment]
@Glennmen Thanks, I'll try to add it asap.

**Comment by Glennmen** [comment]
@leshchenko Also how is the starting point calculated? I want it to start at the top corner.
And thanks for replying so fast!

**Comment by leshchenko** [comment]
@Glennmen First element position below center, and next items draws in a counter-clockwise.

**Comment by Glennmen** [comment]
I am going to see if I can customise this behaviour for me 🤔 if you want I can try to make a PR for it after my adjustments.
This is separate from the orientation/direction 😉I still would like that.

**Comment by leshchenko** [comment]
@Glennmen Just pushed new version with `isClockwise`/`initialAngle` customization. Please see ReadMe.

**Comment by Glennmen** [comment]
@leshchenko Damn you are fast! 😂It looks exactly what I am looking for but will try it out tomorrow at work and let you know.

Right now I am not sure if I should make an other request or make a PR myself, you are fast!

**Comment by leshchenko** [comment]
@Glennmen Re PR, It's up to you. =)
