### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Glennmen** [leshchenko/CircularLayoutManager#7]
I hate opening an issue for this 😅but would it be possible to increase the version and make a new release so that I can use the new disable vertical scrolling.

Or is there anything else you want to include/change before a new version will be made?

Thanks!

**Comment by Glennmen** [comment]
No rush 😎I was able to get the latest version using:
```gradle
implementation 'com.github.leshchenko:CircularLayoutManager:83dd44c70d'
```

**Comment by leshchenko** [comment]
Done.
